service: server

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: personal

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: "{proxy+}"
          method: ANY
          cors: true